name: action
on:
  [ push, pull_request ]
jobs:
  act:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.10.0
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Idle launch
      run: |
        python src/tracert.py
